"""Project initialization and source-ingestion public boundary."""

from rob2_kit.domain.sources import PageCoverage, ParseRecord, ParserQualityPolicy
from rob2_kit.ingestion.project import (
    LITEPARSE_CONFIGURATION,
    PARSER_QUALITY_POLICY,
    RECOVERY_POLICY_RELEASE,
    BoundedZipError,
    DocumentParser,
    LiteParseAdapter,
    OutcomeTarget,
    PageExtraction,
    PageRender,
    PageTextItem,
    PageWord,
    ParserResult,
    ProjectInitialization,
    ProjectManifest,
    ResultCandidate,
    ReviewFinding,
    SourceParseError,
    TrialInitialization,
    initialize_project,
    read_bounded_zip,
)

__all__ = [
    "BoundedZipError",
    "DocumentParser",
    "LiteParseAdapter",
    "LITEPARSE_CONFIGURATION",
    "PageTextItem",
    "PageWord",
    "OutcomeTarget",
    "PageExtraction",
    "PageCoverage",
    "PageRender",
    "ParseRecord",
    "ParserResult",
    "PARSER_QUALITY_POLICY",
    "RECOVERY_POLICY_RELEASE",
    "ParserQualityPolicy",
    "ProjectInitialization",
    "ProjectManifest",
    "ResultCandidate",
    "ReviewFinding",
    "SourceParseError",
    "TrialInitialization",
    "initialize_project",
    "read_bounded_zip",
]
