from __future__ import annotations

import json
import os
import runpy
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

REPOSITORY = Path(__file__).parents[1]
SCRIPTS = REPOSITORY / "scripts"
RUNNER_PATH = SCRIPTS / "run_rsi_case.py"
PREPARER_PATH = SCRIPTS / "prepare_rsi_workspace.py"


def _invoke_failed_run(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    *,
    mode: str,
    relative_run_dir: bool = False,
    runner_bytes: bytes | None = None,
    preparer_bytes: bytes | None = None,
    package_cache: bool = False,
    require_isolated_host: bool = False,
) -> tuple[Path, dict[str, Any]]:
    repo = tmp_path / "fake-repo"
    scripts = repo / "scripts"
    package = repo / "src" / "rob2_kit"
    executable = repo / ".venv" / "Scripts" / "rob2.exe"
    scripts.mkdir(parents=True)
    package.mkdir(parents=True)
    if package_cache:
        cache = package / "__pycache__"
        cache.mkdir()
        (cache / "generated.cpython-313.pyc").write_bytes(b"generated bytecode")
    (scripts / "run_rsi_case.py").write_bytes(runner_bytes or RUNNER_PATH.read_bytes())
    (scripts / "prepare_rsi_workspace.py").write_bytes(preparer_bytes or PREPARER_PATH.read_bytes())
    (package / "__init__.py").write_text("", encoding="utf-8")
    (repo / "pyproject.toml").write_text("project = {}\n", encoding="utf-8")
    (repo / "uv.lock").write_text("version = 1\n", encoding="utf-8")
    executable.parent.mkdir(parents=True)
    executable.write_bytes(b"fake rob2 executable")

    run_dir = tmp_path / "attempt"
    case = tmp_path / "unused-case.json"
    case.write_text("{}", encoding="utf-8")
    prompt = tmp_path / "prompt.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    fake_home = tmp_path / "fake-user-home"
    auth_source = fake_home / ".codex" / "auth.json"
    auth_source.parent.mkdir(parents=True)
    auth_source.write_text('{"fake":"test-only"}', encoding="utf-8")
    monkeypatch.setattr(Path, "home", classmethod(lambda _cls: fake_home))
    if relative_run_dir:
        monkeypatch.chdir(tmp_path)

    def prepare_workspace(_case: Path, workspace: Path) -> dict[str, Any]:
        workspace.mkdir(parents=True)
        (workspace / "input").mkdir()
        skill = workspace / ".agents" / "skills" / "rob2-assess"
        skill.mkdir(parents=True)
        (skill / "SKILL.md").write_text("test skill", encoding="utf-8")
        return {
            "schema": "rob2-kit.rsi-run-inputs.v1",
            "trial": "trial-a",
            "approved_scope": None,
        }

    monkeypatch.syspath_prepend(str(SCRIPTS))
    runner = runpy.run_path(str(RUNNER_PATH))
    runner_globals = runner["main"].__globals__
    runner_globals["__file__"] = str(scripts / "run_rsi_case.py")
    runner_globals["prepare_workspace"] = prepare_workspace
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--case",
            str(case),
            "--prompt",
            str(prompt),
            "--run-dir",
            "attempt" if relative_run_dir else str(run_dir),
            "--phase",
            "1",
        ],
    )
    if require_isolated_host:
        sys.argv.append("--require-isolated-host")

    calls = 0

    def fake_run(command: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        nonlocal calls
        calls += 1
        if "export-skill" in command:
            return subprocess.CompletedProcess(command, 0)
        environment = kwargs["env"]
        codex_home = Path(environment["CODEX_HOME"])
        assert codex_home.is_absolute()
        isolated_auth = codex_home / "auth.json"
        assert isolated_auth.read_text(encoding="utf-8") == '{"fake":"test-only"}'
        # Stand in for files written by the failed Codex process. Cleanup must
        # remove only the temporary credential copy and keep these run outputs.
        (codex_home / "session-state.db").write_bytes(b"fake session state")
        kwargs["stdout"].write(b'{"type":"turn.failed"}\n')
        kwargs["stderr"].write(b"synthetic failure\n")
        last_message = Path(command[command.index("--output-last-message") + 1])
        last_message.write_text("partial output", encoding="utf-8")
        if mode == "raise":
            raise OSError("synthetic Codex launch failure")
        return subprocess.CompletedProcess(command, 17)

    monkeypatch.setattr(subprocess, "run", fake_run)
    monkeypatch.setattr(subprocess, "check_output", lambda *args, **kwargs: "fake-commit")
    if mode == "raise":
        with pytest.raises(OSError, match="synthetic Codex launch failure"):
            runner["main"]()
    else:
        with pytest.raises(SystemExit) as error:
            runner["main"]()
        assert error.value.code == 17
    assert calls == 2
    assert auth_source.read_text(encoding="utf-8") == '{"fake":"test-only"}'
    metadata = json.loads((run_dir / "phase-1.meta.json").read_text(encoding="utf-8"))
    return run_dir, metadata


@pytest.mark.parametrize("mode", ["exit", "raise"])
def test_failed_codex_run_removes_only_isolated_auth_copy(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, mode: str
) -> None:
    run_dir, _metadata = _invoke_failed_run(tmp_path, monkeypatch, mode=mode)

    assert not (run_dir / "codex-home" / "auth.json").exists()
    assert (run_dir / "codex-home" / "session-state.db").read_bytes() == b"fake session state"
    assert (run_dir / "phase-1.jsonl").read_bytes() == b'{"type":"turn.failed"}\n'
    assert (run_dir / "phase-1.stderr.txt").read_bytes() == b"synthetic failure\n"
    assert (run_dir / "phase-1.last-message.txt").read_text(encoding="utf-8") == "partial output"
    assert (run_dir / "phase-1.meta.json").is_file()


def test_build_fingerprint_changes_when_runner_or_preparer_changes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _run_dir, baseline = _invoke_failed_run(tmp_path / "baseline", monkeypatch, mode="exit")
    runner_bytes = RUNNER_PATH.read_bytes() + b"\n# build fingerprint probe\n"
    _run_dir, changed_runner = _invoke_failed_run(
        tmp_path / "runner-change", monkeypatch, mode="exit", runner_bytes=runner_bytes
    )
    preparer_bytes = PREPARER_PATH.read_bytes() + b"\n# build fingerprint probe\n"
    _run_dir, changed_preparer = _invoke_failed_run(
        tmp_path / "preparer-change", monkeypatch, mode="exit", preparer_bytes=preparer_bytes
    )

    assert changed_runner["build_sha256"] != baseline["build_sha256"]
    assert changed_preparer["build_sha256"] != baseline["build_sha256"]


def test_build_fingerprint_ignores_generated_bytecode(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _run_dir, baseline = _invoke_failed_run(tmp_path / "baseline", monkeypatch, mode="exit")
    _run_dir, with_cache = _invoke_failed_run(
        tmp_path / "cache", monkeypatch, mode="exit", package_cache=True
    )

    assert with_cache["build_sha256"] == baseline["build_sha256"]


def test_reused_phase_preserves_all_attempt_artifacts(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir = tmp_path / "attempt"
    run_dir.mkdir()
    originals = {
        ".jsonl": b"original trace\n",
        ".stderr.txt": b"original stderr\n",
        ".last-message.txt": b"original last message",
        ".meta.json": b'{"attempt": 1}\n',
    }
    for suffix, contents in originals.items():
        (run_dir / f"phase-2{suffix}").write_bytes(contents)
    prompt = tmp_path / "prompt.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    monkeypatch.syspath_prepend(str(SCRIPTS))
    runner = runpy.run_path(str(RUNNER_PATH))
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--prompt",
            str(prompt),
            "--run-dir",
            str(run_dir),
            "--phase",
            "2",
            "--session",
            "session-id",
        ],
    )
    with pytest.raises(SystemExit) as error:
        runner["main"]()

    assert error.value.code == 2
    for suffix, contents in originals.items():
        assert (run_dir / f"phase-2{suffix}").read_bytes() == contents


def test_runner_resolves_relative_run_directory(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir, metadata = _invoke_failed_run(
        tmp_path, monkeypatch, mode="exit", relative_run_dir=True
    )

    assert (run_dir / "phase-1.meta.json").is_file()
    assert Path(metadata["command"][metadata["command"].index("-C") + 1]).is_absolute()


@pytest.mark.skipif(os.name == "nt", reason="strict host isolation requires a POSIX host")
def test_required_host_isolation_records_a_deny_by_default_profile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir, metadata = _invoke_failed_run(
        tmp_path, monkeypatch, mode="exit", require_isolated_host=True
    )

    profile = (run_dir / "codex-home" / "config.toml").read_text(encoding="utf-8")
    assert 'default_permissions = "rob2-rsi"' in profile
    assert '":root" = "deny"' in profile
    assert metadata["host_isolation"] == {
        "required": True,
        "policy": "deny-by-default",
    }


@pytest.mark.skipif(os.name == "nt", reason="strict host isolation requires a POSIX host")
def test_continuation_cannot_downgrade_required_host_isolation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir, _metadata = _invoke_failed_run(
        tmp_path, monkeypatch, mode="exit", require_isolated_host=True
    )
    prompt = tmp_path / "continuation.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    runner = runpy.run_path(str(RUNNER_PATH))
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--prompt",
            str(prompt),
            "--run-dir",
            str(run_dir),
            "--phase",
            "2",
            "--session",
            "session-id",
        ],
    )

    with pytest.raises(SystemExit) as error:
        runner["main"]()

    assert error.value.code == 2


def test_required_host_isolation_rejects_windows_without_uac(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    prompt = tmp_path / "prompt.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    run_dir = tmp_path / "attempt"
    monkeypatch.syspath_prepend(str(SCRIPTS))
    runner = runpy.run_path(str(RUNNER_PATH))
    monkeypatch.setitem(runner, "_is_windows", lambda: True)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--prompt",
            str(prompt),
            "--run-dir",
            str(run_dir),
            "--phase",
            "1",
            "--require-isolated-host",
        ],
    )

    with pytest.raises(SystemExit) as error:
        runner["main"]()

    assert error.value.code == 2
    assert not run_dir.exists()
