from __future__ import annotations

import asyncio
import hashlib
import json
import os
import runpy
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any

import pytest

REPOSITORY = Path(__file__).parents[1]
SCRIPTS = REPOSITORY / "scripts"
RUNNER_PATH = SCRIPTS / "run_rsi_case.py"
PREPARER_PATH = SCRIPTS / "prepare_rsi_workspace.py"
CONTRACT_PATH = SCRIPTS / "benchmark_contract.py"


def _invoke_failed_run(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    *,
    mode: str,
    relative_run_dir: bool = False,
    runner_bytes: bytes | None = None,
    preparer_bytes: bytes | None = None,
    contract_bytes: bytes | None = None,
    package_cache: bool = False,
    require_isolated_host: bool = False,
    simulate_posix_isolation: bool = False,
) -> tuple[Path, dict[str, Any]]:
    repo = tmp_path / "fake-repo"
    scripts = repo / "scripts"
    package = repo / "src" / "rob2_kit"
    executable = repo / ".venv" / "Scripts" / "rob2.exe"
    scripts.mkdir(parents=True)
    package.mkdir(parents=True)
    if package_cache:
        cache = package / "__pycache__"
        cache.mkdir()
        (cache / "generated.cpython-313.pyc").write_bytes(b"generated bytecode")
    (scripts / "run_rsi_case.py").write_bytes(runner_bytes or RUNNER_PATH.read_bytes())
    (scripts / "prepare_rsi_workspace.py").write_bytes(preparer_bytes or PREPARER_PATH.read_bytes())
    (scripts / "benchmark_contract.py").write_bytes(contract_bytes or CONTRACT_PATH.read_bytes())
    (scripts / "benchmark_recovery_exec_allowlist.json").write_bytes(
        (SCRIPTS / "benchmark_recovery_exec_allowlist.json").read_bytes()
    )
    (package / "__init__.py").write_text("", encoding="utf-8")
    (repo / "pyproject.toml").write_text("project = {}\n", encoding="utf-8")
    (repo / "uv.lock").write_text("version = 1\n", encoding="utf-8")
    executable.parent.mkdir(parents=True)
    executable.write_bytes(b"fake rob2 executable")
    codex_executable = repo / "codex"
    codex_executable.write_bytes(b"fake codex executable")

    run_dir = tmp_path / "attempt"
    case = tmp_path / "unused-case.json"
    case.write_text("{}", encoding="utf-8")
    prompt = tmp_path / "prompt.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    fake_home = tmp_path / "fake-user-home"
    auth_source = fake_home / ".codex" / "auth.json"
    auth_source.parent.mkdir(parents=True)
    auth_source.write_text('{"fake":"test-only"}', encoding="utf-8")
    monkeypatch.setattr(Path, "home", classmethod(lambda _cls: fake_home))
    monkeypatch.setenv("HOME", str(fake_home))
    monkeypatch.setenv("CODEX_EXECUTABLE", str(codex_executable))
    if relative_run_dir:
        monkeypatch.chdir(tmp_path)

    def prepare_workspace(_case: Path, workspace: Path) -> dict[str, Any]:
        workspace.mkdir(parents=True)
        (workspace / "input").mkdir()
        skill = workspace / ".agents" / "skills" / "rob2-assess"
        skill.mkdir(parents=True)
        (skill / "SKILL.md").write_text("test skill", encoding="utf-8")
        return {
            "schema": "rob2-kit.rsi-run-inputs.v1",
            "trial": "trial-a",
            "approved_scope": None,
            "expected_result": {
                "trial": "trial-a",
                "comparison": [
                    {"id": "A", "assignment": "treatment"},
                    {"id": "B", "assignment": "control"},
                ],
                "endpoint_definition": "death from any cause",
                "population": "all randomized participants",
                "window": "36 months",
                "reported_scope": {
                    "form": "comparative_effect",
                    "analysis_population": "all randomized participants",
                    "endpoint": {"definition": "death from any cause"},
                    "effect_measure": "hazard_ratio",
                    "estimate": "HR 0.75",
                    "precision": "95% CI 0.55 to 1.02",
                },
            },
        }

    monkeypatch.syspath_prepend(str(SCRIPTS))
    runner = runpy.run_path(str(RUNNER_PATH))
    runner_globals = runner["main"].__globals__
    runner_globals["__file__"] = str(scripts / "run_rsi_case.py")
    runner_globals["prepare_workspace"] = prepare_workspace

    def probe_server_inventory(command: Path, workspace: Path) -> dict[str, Any]:
        names = sorted(runner_globals["EXPECTED_TOOL_INVENTORY"])
        binding = {
            "server": "rob2",
            "command": str(command.resolve()),
            "args": ["mcp"],
            "workspace_sha256": hashlib.sha256(
                str(workspace.resolve()).encode("utf-8")
            ).hexdigest(),
        }
        return {
            "status": "verified",
            "source": "stdio tools/list",
            "server": "rob2",
            "names": names,
            "tool_count": len(names),
            "server_binding": binding,
        }

    runner_globals["probe_server_advertised_inventory"] = probe_server_inventory
    runner_globals["_terminate_owned_process"] = lambda _process, **_kwargs: None
    if simulate_posix_isolation or require_isolated_host:
        runner_globals["_is_windows"] = lambda: False
        runner_globals["_preflight_isolation"] = lambda _command, _required: {
            "requested": True,
            "supported": True,
            "sentinel": "denied",
        }
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--case",
            str(case),
            "--prompt",
            str(prompt),
            "--run-dir",
            "attempt" if relative_run_dir else str(run_dir),
            "--phase",
            "1",
        ],
    )
    if require_isolated_host:
        sys.argv.append("--require-isolated-host")

    calls = 0

    def fake_run(command: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        nonlocal calls
        calls += 1
        if "export-skill" in command:
            return subprocess.CompletedProcess(command, 0)
        if command[-1:] == ["mcp"]:
            from rob2_kit.interfaces.mcp.server import mcp

            async def list_tools() -> list[dict[str, Any]]:
                tools = await mcp.list_tools()
                inventory = []
                for tool in tools:
                    annotations = tool.annotations
                    inventory.append(
                        {
                            "name": tool.name,
                            "title": tool.title,
                            "description": tool.description,
                            "inputSchema": tool.parameters,
                            "outputSchema": tool.output_schema,
                            "annotations": {
                                "readOnlyHint": (
                                    annotations.read_only_hint if annotations is not None else False
                                ),
                                "destructiveHint": (
                                    annotations.destructive_hint
                                    if annotations is not None
                                    else False
                                ),
                                "idempotentHint": (
                                    annotations.idempotent_hint
                                    if annotations is not None
                                    else False
                                ),
                                "openWorldHint": (
                                    annotations.open_world_hint
                                    if annotations is not None
                                    else False
                                ),
                            },
                        }
                    )
                return inventory

            response = [
                {
                    "jsonrpc": "2.0",
                    "id": 1,
                    "result": {"serverInfo": {"name": "rob2", "version": "test"}},
                },
                {
                    "jsonrpc": "2.0",
                    "id": 2,
                    "result": {"tools": asyncio.run(list_tools())},
                },
            ]
            return subprocess.CompletedProcess(
                command,
                0,
                stdout="\n".join(json.dumps(item) for item in response) + "\n",
                stderr="",
            )
        environment = kwargs["env"]
        codex_home = Path(environment["CODEX_HOME"])
        assert codex_home.is_absolute()
        isolated_auth = codex_home / "auth.json"
        assert isolated_auth.read_text(encoding="utf-8") == '{"fake":"test-only"}'
        # Stand in for files written by the failed Codex process. Cleanup must
        # remove only the temporary credential copy and keep these run outputs.
        (codex_home / "session-state.db").write_bytes(b"fake session state")
        kwargs["stdout"].write(b'{"type":"turn.failed"}\n')
        kwargs["stderr"].write(b"synthetic failure\n")
        last_message = Path(command[command.index("--output-last-message") + 1])
        last_message.write_text("partial output", encoding="utf-8")
        if mode == "raise":
            raise OSError("synthetic Codex launch failure")
        return subprocess.CompletedProcess(command, 17)

    monkeypatch.setattr(subprocess, "run", fake_run)
    monkeypatch.setattr(subprocess, "check_output", lambda *args, **kwargs: "fake-commit")

    class FakePopen:
        def __init__(self, command: list[str], **kwargs: Any) -> None:
            nonlocal calls
            calls += 1
            self.command = command
            self.kwargs = kwargs
            self.returncode: int | None = None
            if require_isolated_host:
                environment = kwargs["env"]
                assert "ROB2_RSI_PREFLIGHT_SECRET" not in environment
                assert "OPENAI_API_KEY" not in environment

        def communicate(
            self, input: bytes | None = None, timeout: float | None = None
        ) -> tuple[bytes, bytes]:
            del input
            del timeout
            environment = self.kwargs["env"]
            codex_home = Path(environment["CODEX_HOME"])
            assert codex_home.is_absolute()
            isolated_auth = codex_home / "auth.json"
            assert isolated_auth.read_text(encoding="utf-8") == '{"fake":"test-only"}'
            (codex_home / "session-state.db").write_bytes(b"fake session state")
            self.kwargs["stdout"].write(b'{"type":"turn.failed"}\n')
            self.kwargs["stderr"].write(b"synthetic failure\n")
            last_message = Path(self.command[self.command.index("--output-last-message") + 1])
            last_message.write_text("partial output", encoding="utf-8")
            if mode == "raise":
                raise OSError("synthetic Codex launch failure")
            self.returncode = 17
            return b"", b""

        def poll(self) -> int | None:
            return self.returncode

        def kill(self) -> None:
            self.returncode = -9

        def wait(self) -> int | None:
            return self.returncode

    monkeypatch.setattr(subprocess, "Popen", FakePopen)
    runner["main"].__globals__["_windows_job_guard"] = lambda _process: None
    if mode == "raise":
        with pytest.raises(OSError, match="synthetic Codex launch failure"):
            runner["main"]()
    else:
        with pytest.raises(SystemExit) as error:
            runner["main"]()
        assert error.value.code == 17
    assert calls == 2
    assert auth_source.read_text(encoding="utf-8") == '{"fake":"test-only"}'
    metadata = json.loads((run_dir / "phase-1.meta.json").read_text(encoding="utf-8"))
    return run_dir, metadata


@pytest.mark.parametrize("mode", ["exit", "raise"])
def test_failed_codex_run_removes_only_isolated_auth_copy(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, mode: str
) -> None:
    runner = runpy.run_path(str(RUNNER_PATH))
    stale_home = runner["_codex_home_path"](tmp_path / "attempt")
    stale_home.mkdir(mode=0o700, parents=True, exist_ok=True)
    (stale_home / "auth.json").write_text('{"stale":"credential"}', encoding="utf-8")
    run_dir, metadata = _invoke_failed_run(tmp_path, monkeypatch, mode=mode)
    codex_home = Path(metadata["runtime_inputs"]["codex_home_path"])

    assert not (run_dir / "codex-home").exists()
    assert not (codex_home / "auth.json").exists()
    assert (codex_home / "session-state.db").read_bytes() == b"fake session state"
    assert (run_dir / "phase-1.jsonl").read_bytes() == b'{"type":"turn.failed"}\n'
    assert (run_dir / "phase-1.stderr.txt").read_bytes() == b"synthetic failure\n"
    assert (run_dir / "phase-1.last-message.txt").read_text(encoding="utf-8") == "partial output"
    assert (run_dir / "phase-1.meta.json").is_file()


@pytest.mark.skipif(os.name == "nt", reason="POSIX directory ownership/mode checks")
def test_codex_home_refuses_symlinked_session_directory(tmp_path: Path) -> None:
    runner = runpy.run_path(str(RUNNER_PATH))
    target = tmp_path / "target"
    target.mkdir()
    parent = tmp_path / "private"
    parent.mkdir(mode=0o700)
    linked = parent / "case"
    linked.symlink_to(target, target_is_directory=True)

    with pytest.raises(ValueError, match="must be a real directory"):
        runner["_prepare_codex_home"](linked)


def test_build_fingerprint_changes_when_runner_or_preparer_changes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _run_dir, baseline = _invoke_failed_run(tmp_path / "baseline", monkeypatch, mode="exit")
    runner_bytes = RUNNER_PATH.read_bytes() + b"\n# build fingerprint probe\n"
    _run_dir, changed_runner = _invoke_failed_run(
        tmp_path / "runner-change", monkeypatch, mode="exit", runner_bytes=runner_bytes
    )
    preparer_bytes = PREPARER_PATH.read_bytes() + b"\n# build fingerprint probe\n"
    _run_dir, changed_preparer = _invoke_failed_run(
        tmp_path / "preparer-change", monkeypatch, mode="exit", preparer_bytes=preparer_bytes
    )

    assert changed_runner["build_sha256"] != baseline["build_sha256"]
    assert changed_preparer["build_sha256"] != baseline["build_sha256"]
    contract_bytes = CONTRACT_PATH.read_bytes() + b"\n# build fingerprint probe\n"
    _run_dir, changed_contract = _invoke_failed_run(
        tmp_path / "contract-change", monkeypatch, mode="exit", contract_bytes=contract_bytes
    )
    assert changed_contract["build_sha256"] != baseline["build_sha256"]


def test_build_fingerprint_ignores_generated_bytecode(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _run_dir, baseline = _invoke_failed_run(tmp_path / "baseline", monkeypatch, mode="exit")
    _run_dir, with_cache = _invoke_failed_run(
        tmp_path / "cache", monkeypatch, mode="exit", package_cache=True
    )

    assert with_cache["build_sha256"] == baseline["build_sha256"]


def test_reused_phase_preserves_all_attempt_artifacts(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir = tmp_path / "attempt"
    run_dir.mkdir()
    originals = {
        ".jsonl": b"original trace\n",
        ".stderr.txt": b"original stderr\n",
        ".last-message.txt": b"original last message",
        ".meta.json": b'{"attempt": 1}\n',
    }
    for suffix, contents in originals.items():
        (run_dir / f"phase-2{suffix}").write_bytes(contents)
    prompt = tmp_path / "prompt.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    monkeypatch.syspath_prepend(str(SCRIPTS))
    runner = runpy.run_path(str(RUNNER_PATH))
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--prompt",
            str(prompt),
            "--run-dir",
            str(run_dir),
            "--phase",
            "2",
            "--session",
            "session-id",
        ],
    )
    with pytest.raises(SystemExit) as error:
        runner["main"]()

    assert error.value.code == 2
    for suffix, contents in originals.items():
        assert (run_dir / f"phase-2{suffix}").read_bytes() == contents


def test_runner_resolves_relative_run_directory(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir, metadata = _invoke_failed_run(
        tmp_path, monkeypatch, mode="exit", relative_run_dir=True
    )

    assert (run_dir / "phase-1.meta.json").is_file()
    assert Path(metadata["command"][metadata["command"].index("-C") + 1]).is_absolute()


def test_runner_gives_the_local_mcp_server_realistic_timeouts(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _run_dir, metadata = _invoke_failed_run(tmp_path, monkeypatch, mode="exit")

    codex_config = Path(metadata["codex_mcp_config"]["path"])
    config = tomllib.loads(codex_config.read_text(encoding="utf-8"))
    server = config["mcp_servers"]["rob2"]
    assert server["startup_timeout_sec"] == 120
    assert server["tool_timeout_sec"] == 600
    assert metadata["codex_mcp_config"]["snapshot_path"] == "phase-1.codex-config.toml"
    assert (
        metadata["codex_mcp_config"]["snapshot_sha256"]
        == hashlib.sha256(codex_config.read_bytes()).hexdigest()
    )
    assert metadata["runtime_inputs"]["codex_mcp_tool_timeout_sec"] == 600


@pytest.mark.skipif(os.name == "nt", reason="strict host isolation requires a POSIX host")
def test_required_host_isolation_records_a_deny_by_default_profile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir, metadata = _invoke_failed_run(
        tmp_path, monkeypatch, mode="exit", require_isolated_host=True
    )

    profile = (Path(metadata["runtime_inputs"]["codex_home_path"]) / "config.toml").read_text(
        encoding="utf-8"
    )
    assert 'default_permissions = "rob2-rsi"' in profile
    assert '":root" = "deny"' in profile
    protected_paths = (run_dir, Path(tempfile.gettempdir()), Path.home() / ".codex")
    for path in protected_paths:
        assert f'{json.dumps(path.as_posix())} = "deny"' in profile
    assert metadata["host_isolation"] == {
        "required": True,
        "policy": "deny-by-default",
    }


_PROTECTED_PROBE_NAMES = (
    "sentinel",
    "run_inputs",
    "approved_scope",
    "codex_auth",
    "execution",
    "source_auth",
    "sibling_codex_auth",
    "sibling_run_inputs",
    "outside_temp",
)
_ALL_PROBE_DENIALS = "ENV:clean\nALLOWED:read_write\n" + "".join(
    f"DENIED:{name}\nDENIED_WRITE:{name}\n" for name in _PROTECTED_PROBE_NAMES
)


@pytest.mark.parametrize(
    "probe_output, expected_error",
    [
        (_ALL_PROBE_DENIALS, None),
        (
            _ALL_PROBE_DENIALS.replace("DENIED:codex_auth\n", "READ:codex_auth\n"),
            "a protected file was readable",
        ),
        (
            _ALL_PROBE_DENIALS.replace("DENIED:sibling_run_inputs\n", ""),
            "did not deny protected files: sibling_run_inputs",
        ),
        (
            _ALL_PROBE_DENIALS.replace("ALLOWED:read_write", "ALLOWED:denied"),
            "did not verify workspace read/write access",
        ),
    ],
)
def test_isolation_preflight_probes_run_inputs_approved_scope_and_auth(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    probe_output: str,
    expected_error: str | None,
) -> None:
    runner = runpy.run_path(str(RUNNER_PATH))
    monkeypatch.setitem(runner["_preflight_isolation"].__globals__, "_is_windows", lambda: False)
    monkeypatch.setenv("ROB2_RSI_PREFLIGHT_SECRET", "test-secret")
    monkeypatch.setenv("OPENAI_API_KEY", "test-api-key")
    captured_profile: dict[str, str] = {}

    def fake_check_output(command: list[str], **kwargs: Any) -> str:
        if command[1] == "sandbox":
            config = Path(kwargs["env"]["CODEX_HOME"]) / "config.toml"
            captured_profile["text"] = config.read_text(encoding="utf-8")
            assert Path(kwargs["env"]["TMPDIR"]) == Path(kwargs["cwd"]) / ".tmp"
            assert kwargs["env"]["TMP"] == kwargs["env"]["TMPDIR"]
            assert kwargs["env"]["TEMP"] == kwargs["env"]["TMPDIR"]
            assert "ROB2_RSI_PREFLIGHT_SECRET" not in kwargs["env"]
            assert "OPENAI_API_KEY" not in kwargs["env"]
            return probe_output
        return "Codex test version"

    monkeypatch.setattr(subprocess, "check_output", fake_check_output)
    if expected_error is None:
        result = runner["_preflight_isolation"](Path("codex"), True)
        assert result["sentinel"] == "denied"
    else:
        with pytest.raises(RuntimeError, match=expected_error):
            runner["_preflight_isolation"](Path("codex"), True)

    profile = captured_profile["text"]
    deny_lines = [line for line in profile.splitlines() if line.endswith(' = "deny"')]
    assert any(line.endswith('/run-inputs.json" = "deny"') for line in deny_lines)
    assert any(line.endswith('/approved-scope.json" = "deny"') for line in deny_lines)
    assert any(line.endswith('/auth.json" = "deny"') for line in deny_lines)
    assert any(line.endswith('/forbidden sentinel.txt" = "deny"') for line in deny_lines)
    assert '":tmpdir" = "write"' not in profile
    assert '":slash_tmp" = "write"' not in profile
    environment = runner["_codex_environment"](
        Path("/tmp/codex"), Path("/tmp/workspace"), strict=True, base={"PATH": "bin"}
    )
    assert environment["TMPDIR"] == "/tmp/workspace/.tmp"


def test_strict_launch_denies_scope_and_auth_files_on_any_host(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("ROB2_RSI_PREFLIGHT_SECRET", "test-secret")
    monkeypatch.setenv("OPENAI_API_KEY", "test-api-key")
    run_dir, metadata = _invoke_failed_run(
        tmp_path,
        monkeypatch,
        mode="exit",
        require_isolated_host=True,
        simulate_posix_isolation=True,
    )
    profile = (Path(metadata["runtime_inputs"]["codex_home_path"]) / "config.toml").read_text(
        encoding="utf-8"
    )
    protected_paths = (run_dir, Path.home() / ".codex", Path(tempfile.gettempdir()))
    for path in protected_paths:
        assert f'{json.dumps(path.as_posix())} = "deny"' in profile
    assert '":tmpdir" = "write"' not in profile
    assert '":slash_tmp" = "write"' not in profile


@pytest.mark.skipif(os.name == "nt", reason="strict host isolation requires a POSIX host")
def test_continuation_cannot_downgrade_required_host_isolation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    run_dir, _metadata = _invoke_failed_run(
        tmp_path, monkeypatch, mode="exit", require_isolated_host=True
    )
    prompt = tmp_path / "continuation.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    runner = runpy.run_path(str(RUNNER_PATH))
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--prompt",
            str(prompt),
            "--run-dir",
            str(run_dir),
            "--phase",
            "2",
            "--session",
            "session-id",
        ],
    )

    with pytest.raises(SystemExit) as error:
        runner["main"]()

    assert error.value.code == 2


def test_required_host_isolation_rejects_windows_without_uac(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    prompt = tmp_path / "prompt.txt"
    prompt.write_text("Continue.\n", encoding="utf-8")
    run_dir = tmp_path / "attempt"
    monkeypatch.syspath_prepend(str(SCRIPTS))
    runner = runpy.run_path(str(RUNNER_PATH))
    monkeypatch.setitem(runner["main"].__globals__, "_is_windows", lambda: True)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            str(RUNNER_PATH),
            "--prompt",
            str(prompt),
            "--run-dir",
            str(run_dir),
            "--phase",
            "1",
            "--require-isolated-host",
        ],
    )

    with pytest.raises(SystemExit) as error:
        runner["main"]()

    assert error.value.code == 2
    assert not run_dir.exists()
